In [1]:
import sys
sys.path.append("../source")

from Match_Analytics import Match

# Match initialization

To initialize a match and preprocess the tracking data you must instantiate an object Match() indicating the data source, the match id and optional additional arguments. Following that the method preprocess() can be called on the Match() object.

In [2]:
match_1 = Match(data_source = 'metrica-sports', match_id = 1, name = "Sample_Game_1", field_dimen=(106., 68.))

# Initially the dataframe values are raw from the source, to preprocess the data a method must be called:
match_2 = Match('metrica-sports',2).preprocess() # Minimum number of positional arguments: (data_source, match_id)

Reading team: home
Reading team: away
Reading team: home
Reading team: away

In [6]:
match_1.preprocess()

match_1.tracking_home

,Period,Time [s],Home_11_x,Home_11_y,Home_1_x,Home_1_y,Home_2_x,Home_2_y,Home_3_x,Home_3_y,...,Home_6_speed,Home_7_vx,Home_7_vy,Home_7_speed,Home_8_vx,Home_8_vy,Home_8_speed,Home_9_vx,Home_9_vy,Home_9_speed
Frame,,,,,,,,,,,,,,,,,,,,,
1,1,0.04,-52.91308,1.19816,-18.39312,-10.41896,-17.27694,0.77316,-20.21738,9.84028,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,0.08,-52.89824,1.19816,-18.39312,-10.41896,-17.27694,0.77316,-20.21738,9.84028,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,0.12,-52.87916,1.19816,-18.39312,-10.41896,-17.27694,0.77316,-20.21738,9.84028,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,0.16,-52.87174,1.19816,-18.42068,-10.41556,-17.29178,0.68816,-20.19936,9.82328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,0.20,-52.86326,1.19816,-18.44718,-10.38292,-17.31616,0.66776,-20.19512,9.84096,...,0.81149,0.590571,1.369714,1.491607,-0.049214,1.806857,1.807527,0.208214,1.296857,1.313466
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145002,2,5800.08,-43.05084,3.15860,NaN,NaN,16.79358,-9.92664,19.89832,-11.90884,...,NaN,0.000000,0.000000,0.000000,0.374786,-0.170000,0.411539,-0.280143,0.551286,0.618382
145003,2,5800.12,-42.98300,3.15860,NaN,NaN,16.82538,-9.91644,19.89620,-11.91972,...,NaN,0.000000,0.000000,0.000000,0.488357,-0.228286,0.539080,0.037857,0.731000,0.731980
145004,2,5800.16,-42.92152,3.15860,NaN,NaN,16.86566,-9.90692,19.91316,-11.90068,...,NaN,0.000000,0.000000,0.000000,0.654929,-0.366107,0.750311,0.395607,0.813571,0.904657
145005,2,5800.20,-42.88336,3.15792,NaN,NaN,16.90064,-9.89536,19.95874,-11.87824,...,NaN,0.000000,0.000000,0.000000,0.821500,-0.503929,0.963746,0.753357,0.896143,1.170734
145006,2,5800.24,-42.88336,3.15792,NaN,NaN,16.96424,-9.88992,20.01068,-11.92176,...,NaN,0.000000,0.000000,0.000000,0.988071,-0.641750,1.178189,1.111107,0.978714,1.480689

In [3]:
match_1.tracking_away

,Period,Time [s],Away_25_x,Away_25_y,Away_15_x,Away_15_y,Away_16_x,Away_16_y,Away_17_x,Away_17_y,...,Away_24_x,Away_24_y,Away_26_x,Away_26_y,Away_27_x,Away_27_y,Away_28_x,Away_28_y,ball_x,ball_y
Frame,,,,,,,,,,,,,,,,,,,,,
1,1,0.04,0.90509,0.47462,0.58393,0.20794,0.67658,0.46710,0.67310,0.76476,...,0.37833,0.27383,NaN,NaN,NaN,NaN,NaN,NaN,0.45472,0.38709
2,1,0.08,0.90494,0.47462,0.58393,0.20794,0.67658,0.46710,0.67310,0.76476,...,0.37833,0.27383,NaN,NaN,NaN,NaN,NaN,NaN,0.49645,0.40656
3,1,0.12,0.90434,0.47463,0.58393,0.20794,0.67658,0.46710,0.67310,0.76476,...,0.37833,0.27383,NaN,NaN,NaN,NaN,NaN,NaN,0.53716,0.42556
4,1,0.16,0.90377,0.47463,0.58351,0.20868,0.67640,0.46762,0.67279,0.76542,...,0.37756,0.27473,NaN,NaN,NaN,NaN,NaN,NaN,0.55346,0.42231
5,1,0.20,0.90324,0.47464,0.58291,0.21039,0.67599,0.46769,0.67253,0.76564,...,0.37663,0.27543,NaN,NaN,NaN,NaN,NaN,NaN,0.55512,0.40570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145002,2,5800.08,0.12564,0.55386,0.17876,0.56826,0.25818,0.59952,0.09880,0.92391,...,NaN,NaN,0.35600,0.55371,0.19836,0.45137,0.21798,0.81079,NaN,NaN
145003,2,5800.12,0.12564,0.55386,0.17838,0.56727,0.25799,0.59999,0.09880,0.92391,...,NaN,NaN,0.35583,0.55283,0.19831,0.45182,0.21798,0.81079,NaN,NaN
145004,2,5800.16,0.12564,0.55386,0.17792,0.56682,0.25757,0.60019,0.09880,0.92391,...,NaN,NaN,0.35561,0.55254,0.19805,0.45200,0.21798,0.81079,NaN,NaN
145005,2,5800.20,0.12564,0.55386,0.17730,0.56621,0.25721,0.60089,0.09880,0.92391,...,NaN,NaN,0.35532,0.55243,0.19766,0.45237,0.21798,0.81079,NaN,NaN
145006,2,5800.24,0.12564,0.55386,0.17693,0.56675,0.25659,0.60072,0.09880,0.92391,...,NaN,NaN,0.35495,0.55364,0.19754,0.45364,0.21798,0.81079,NaN,NaN

In [4]:
match_1.events

,Team,Type,Subtype,Period,Start Frame,Start Time [s],End Frame,End Time [s],From,To,Start X,Start Y,End X,End Y
0,Away,SET PIECE,KICK OFF,1,1,0.04,0,0.00,Player19,NaN,NaN,NaN,NaN,NaN
1,Away,PASS,NaN,1,1,0.04,3,0.12,Player19,Player21,0.45,0.39,0.55,0.43
2,Away,PASS,NaN,1,3,0.12,17,0.68,Player21,Player15,0.55,0.43,0.58,0.21
3,Away,PASS,NaN,1,45,1.80,61,2.44,Player15,Player19,0.55,0.19,0.45,0.31
4,Away,PASS,NaN,1,77,3.08,96,3.84,Player19,Player21,0.45,0.32,0.49,0.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1740,Home,PASS,NaN,2,143361,5734.44,143483,5739.32,Player12,Player13,0.60,0.33,0.19,0.95
1741,Home,PASS,NaN,2,143578,5743.12,143593,5743.72,Player13,Player4,0.09,0.88,0.14,0.69
1742,Home,BALL LOST,INTERCEPTION,2,143598,5743.92,143618,5744.72,Player4,NaN,0.13,0.69,0.07,0.61
1743,Away,RECOVERY,BLOCKED,2,143617,5744.68,143617,5744.68,Player16,NaN,0.05,0.62,NaN,NaN
1744,Away,BALL OUT,NaN,2,143622,5744.88,143630,5745.20,Player16,NaN,0.05,0.63,0.03,1.01

In [8]:
match_1.calculate_player_normals()

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().